# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
