# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='rooms.Message')),
            ],
        ),
    ]
