# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_newmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_room',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default='jolas', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.Room'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
